# Copyright 2018 Tobias Weber weber@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Set fact for the docker registry credentials
  set_fact:
    registry_config: "{{ lookup('file', 'registry_config') | b64encode }}"

- name: Set fact for the bookmark mongodb credentials
  set_fact:
    BOOKMARK_MONGODB_PASSWORD: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

- name: Set fact for the harvest mongodb credentials
  set_fact:
    HARVEST_MONGODB_PASSWORD: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

- name: Create Templates for secrets
  template:
    src: "{{ item }}-secret.yml.j2"
    dest: "{{ K8S_BASE_DIR }}/{{ item }}-secret.yml"
    mode: '0400'
  with_items:
    - lrz-docker-registry
    - bookmark-mongodb
    - harvest-mongodb

- name: Set secret for docker registry
  shell: |
    kubectl apply -f {{ K8S_BASE_DIR }}/{{ item }}-secret.yml
  with_items:
    - lrz-docker-registry
    - bookmark-mongodb
    - harvest-mongodb

- name: Delete secrets on filesystem
  file:
    path: "{{ K8S_BASE_DIR }}/{{ item }}-secret.yml"
    state: absent
  with_items:
    - lrz-docker-registry
    - bookmark-mongodb
    - harvest-mongodb
