- name: Set fact for the docker registry credentials
  set_fact:
    registry_config: "{{ lookup('file', 'registry_config') | b64encode }}"

- name: Create Template for lrz-docker-registry-secret.yml
  template:
    src: lrz-docker-registry-secret.yml.j2
    dest: "{{ K8S_BASE_DIR }}/lrz-docker-registry-secret.yml"
    mode: '0400'

- name: Set secret for docker registry
  shell: |
    kubectl apply -f {{ K8S_BASE_DIR }}/lrz-docker-registry-secret.yml
