# Copyright 2018 Walentin Lamonos lamonos@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# Description:
# Performs the network interface setup on vmware loadbalancer nodes
# Making sure it uses systemd-networkd

- name: Backup Default Configuration
  copy:
    src: /etc/network/interfaces
    dest: /etc/network/interfaces.bak
    remote_src: yes
  when: inventory_hostname in groups['loadbalancer_nodes']

- name: Replace /etc/network/interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  when: inventory_hostname in groups['loadbalancer_nodes']

- name: Restart Network Interfaces
  service:
    name: networking
    state: restarted
  ignore_errors: yes
  when: inventory_hostname in groups['loadbalancer_nodes']
