---
- name: Install conntrack
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - conntrack
    - conntrackd

- name: Flush iptables rules
  iptables:
    table: nat
    flush: yes

- name: Symlink kube-proxy to /usr/bin
  file:
    src:    "{{ K8S_SERVER_BIN_DIR }}/kube-proxy"
    dest:   "/usr/bin/kube-proxy"
    state:  link

- name: Create a systemd unit file
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
  notify:
    - reload daemon
    - restart kube-proxy

- name: Register kube-proxy to systemd
  systemd:
    state: started
    name: kube-proxy
    enabled: yes
    daemon-reload: yes

- name: Allow forwarding from extern IPs to NodeIPs
  iptables:
    chain: FORWARD
    policy: ACCEPT
