# Copyright 2019 Nelson Tavares de Sousa tavaresdesousa@email.uni-kiel.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: keycloak | Check whether keycloak chart is already installed
  shell: |
    kubectl get pods  \
      --selector=app=keycloak \
      --field-selector=status.phase=Running
  register: keycloakInstalled

- name: keycloak | Check whether postgresql chart is already installed
  shell: |
    kubectl get pods  \
      --selector=app=postgresql \
      --field-selector=status.phase=Running
  register: postgresqlInstalled

- name: keycloak | Update repos
  shell: helm repo update
  when: keycloakInstalled.stdout.find("Running") == -1

- name: keycloak | Install postgres
  shell: |
    helm install \
      --name postgres \
      --set postgresqlDatabase=keycloak \
      stable/postgresql
  when: postgresqlInstalled.stdout.find("Running") == -1

- name: keycloak | Install keycloak
  shell: |
    helm install \
      --name keycloak \
      --set keycloak.basepath={{ KEYCLOAK_BASEPATH }} \
      --set keycloak.persistence.existingSecret=postgres-postgresql \
      --set keycloak.persistence.existingSecretKey=postgresql-password \
      --set keycloak.persistence.dbVendor=postgres \
      --set keycloak.persistence.dbHost=postgres-postgresql.default.svc.cluster.local \
      --set keycloak.persistence.dbUser=postgres \
      stable/keycloak
  async: 60
  poll: 60
  when: keycloakInstalled.stdout.find("Running") == -1
