- name: Initialize kubernetes nodes
  hosts: kubernetes-masters
  remote_user: root
  roles:
    - common
    - etcd
    - k8s-binaries
    # docker, kubelet and kube-proxy are only installed on the master
    # if one of the following services need it to be run as a pod.
    - docker
    - cni
    - kubelet
    - kube-proxy
    - apiserver
    - scheduler
    - controller-manager
    - network_ovn
    - k8s-addons
