- name: Initialize kubernetes nodes
  hosts: kubernetes-masters
  remote_user: root
  roles:
    - common
    - etcd
    - k8s-binaries
    - docker
    - cni
    - kubelet
    - kube-proxy
    - apiserver
    - scheduler
    - controller-manager
    - network_ovn
    - k8s-addons
