---
- name: Symlink kubelet to /usr/bin
  file:
    src:    "{{ K8S_SERVER_BIN_DIR }}/kubelet"
    dest:   "/usr/bin/kubelet"
    state:  link

- name: Create a kubelet environment file
  template:
    src: kubelet.j2
    dest: /etc/kubernetes/kubelet

- name: Create a systemd unit file
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify:
    - restart kubelet

- name: Register kubelet to systemd
  systemd:
    state: started
    name: kubelet
    enabled: yes
    daemon-reload: yes
