---
- name: Symlink controller-manager to /usr/bin
  file:
    src:    "{{ K8S_SERVER_BIN_DIR }}/kube-controller-manager"
    dest:   "/usr/bin/controller-manager"
    state:  link

- name: Create a systemd unit file
  template:
    src: controller-manager.service.j2
    dest: /etc/systemd/system/controller-manager.service
  notify:
    - reload daemon
    - restart controller-manager

- name: Register controller-manager to systemd
  systemd:
    state: started
    name: controller-manager
    enabled: yes
    daemon-reload: yes
