- name: install ovs and ovn node packages
  package:
    name={{ item }}
    state=present
  with_items:
    - ovn-host

- name: Set the k8s API server address in the Open vSwitch database
  shell: ovs-vsctl set Open_vSwitch . external_ids:k8s-api-server="{{MASTER_IP}}:8080"

- name: Actually inizitalize node
  shell: ovn-k8s-overlay minion-init --cluster-ip-subnet="{{ CLUSTER_IP_SUBNET }}" --minion-switch-subnet="{{MINION_SWITCH_SUBNET}}" --node-name="{{ ansible_hostname}}"
