- name: install ovs and ovn node packages
  package:
    name={{ item }}
    state=present
  with_items:
    - ovn-host

- name: Create OVN configuration
  template:
    src: ovn_k8s.conf.j2
    dest: /etc/openvswitch/ovn_k8s.conf

- name: Secure connection to k8s API server
  shell: ovs-vsctl set Open_vSwitch . external_ids:{{item}}
  with_items:
    - k8s-api-server=https://{{ K8S_MASTER_IP }}
    - k8s-ca-certificate={{ K8S_CERT_FILES_DIR }}/ca.crt.pem
    - k8s-api-token={{ OVN_API_TOKEN }}

- name: Actually inizitalize node
  shell: |
    ovn-k8s-overlay minion-init \
      --cluster-ip-subnet={{ K8S_CLUSTER_IP_SUBNET }} \
      --minion-switch-subnet={{ SUBNET_IP_PRE }}.{{ hostname_suffix }}.0/24 \
      --node-name={{ inventory_hostname }}

- name: Install ovn-k8s-gateway-init as a service
  template:
    src: ovn-k8s-gateway-init.service.j2
    dest: /etc/systemd/system/ovn-k8s-gateway-init.service
  when: secondInterface.rc != 100

- name: Install ovn-k8s-gateway-init script
  template:
    src:  ovn-k8s-gateway-init.sh.j2
    dest: "{{ OVN_K8S_DIR }}/ovn-k8s-gateway-init.sh"
    mode: 0755
  when: secondInterface.rc != 100

- name: Register ovn-k8s-gateway-init to systemd and start it
  systemd:
    name: ovn-k8s-gateway-init.service
    enabled: yes
    daemon-reload: yes
  when: secondInterface.rc == 100

- name: Install ovn-k8s-gateway-helper as a service
  template:
    src: ovn-k8s-gateway-helper.service.j2
    dest: /etc/systemd/system/ovn-k8s-gateway-helper.service
  when: secondInterface.rc != 100

- name: Register ovn-k8s-gateway-helper to systemd
  systemd:
    name: ovn-k8s-gateway-helper.service
    enabled: yes
    daemon-reload: yes

- name: Start ovn-k8s-gateway
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - ovn-k8s-gateway-init.service
    - ovn-k8s-gateway-helper.service
