- name: install ovs and ovn node packages
  package:
    name={{ item }}
    state=present
  with_items:
    - ovn-host

- name: Create OVN configuration
  template:
    src: ovn_k8s.conf.j2
    dest: /etc/openvswitch/ovn_k8s.conf

- name: Secure connection to k8s API server
  shell: ovs-vsctl set Open_vSwitch . external_ids:{{item}}
  with_items:
    - k8s-api-server=https://{{ K8S_MASTER_IP }}
    - k8s-ca-certificate={{ K8S_CERT_FILES_DIR }}/ca.crt.pem
    - k8s-api-token={{ OVN_API_TOKEN }}

- name: Install ovn-k8s-init as a service
  template:
    src: ovn-k8s-init.service.j2
    dest: /etc/systemd/system/ovn-k8s-init.service

- name: Install ovn-k8s-init script
  template:
    src:  ovn-k8s-init.sh.j2
    dest: "{{ OVN_K8S_DIR }}/ovn-k8s-init.sh"
    mode: 0755
  notify:
    - start ovn-k8s-init

- name: Register ovn-k8s-init to systemd and start it
  systemd:
    name: ovn-k8s-init.service
    enabled: yes
    daemon-reload: yes
