# Copyright 2018 Tobias Weber weber@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Add unstable for newer ovn-version
  apt_repository:
    repo: deb http://debian.mirror.lrz.de/debian unstable main
    state: present

- name: Install package pinning for newer ovn-version
  copy:
    src: ovnovs.pref
    dest: /etc/apt/preferences.d/ovnovs.pref

- name: Install ovn dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - openvswitch-switch
    - python-pip
    - virtualenv

#- name: Install ovn controller systemd unit file
#  template:
#    src: ovn-controller.service.j2
#    dest: /etc/systemd/system/ovn-controller.service
#
#- name: Reload systemd daemon and start ovn controller
#  systemd:
#    state: started
#    name: ovn-controller
#    enabled: yes
#    daemon-reload: yes

- name: Set db entries on both masters and nodes
  shell: ovs-vsctl set Open_vSwitch . external_ids:{{item}}
  with_items:
    - ovn-remote="tcp:{{ K8S_MASTER_IP }}:6642"
    - ovn-nb="tcp:{{ K8S_MASTER_IP }}:6641"
    - ovn-encap-ip="{{ internalIP }}"
    - ovn-encap-type="{{ OVN_ENCAP_TYPE }}"

# TODO: version should sometime be specified to guarantee that it works
- name: Pull k8s ovn integration scripts
  git:
    repo: 'https://github.com/openvswitch/ovn-kubernetes.git'
    version: "branch-0.5"
    dest: "{{ OVN_K8S_DIR }}"

- name: Update pip
  pip:
    name: pip
    state: latest

- name: Install python requirements for k8s ovn integration scripts
  pip:
    requirements: "{{ OVN_K8S_DIR }}/requirements.txt"

- name: Install k8s ovn integration scripts
  shell: "pip install ."
  args:
    chdir: "{{ OVN_K8S_DIR }}"
