- name: Set db entries on both masters and nodes
  shell: ovs-vsctl set Open_vSwitch . external_ids:{{item}}
  with_items:
    - ovn-remote="tcp:{{MASTER_IP}}:6642"
    - ovn-nb="tcp:{{MASTER_IP}}:6641"
    - ovn-encap-ip={{ansible_default_ipv4.address}}
    - ovn-encap-type="{{ENCAP_TYPE}}"
