apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: kube-monitor
spec:
  selector:
    app: prometheus-server
    service: monitoring
  ports:
  - port: 9090
    protocol: TCP
