---
# create canonical place for certs and keys on control machine
- name: Create directory for certs and keys on control machine
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_items:
    - { path: "{{CONTROL_BASE_DIR}}"  , mode: '0700' }
    - { path: "{{CONTROL_CERT_DIR}}"  , mode: '0700' }
    - { path: "{{CONTROL_KEY_DIR}}"   , mode: '0700' }
    - { path: "{{CONTROL_CONFIG_DIR}}", mode: '0700' }
    - { path: "{{CONTROL_CSR_DIR}}"   , mode: '0700' }

# create keys and certs and sign them
- name: Create keys and certs and sign them
  include_tasks: createKeysAndCertsAndSignThem.yml extensions={{ item.extensions }} filename={{ item.filename }} d_name={{ item.d_name }} sign={{ item.sign }}
  with_items:
    - { extensions: "-extensions v3_ca",
        filename:   "ca",
        d_name:     "{{ MASTER_IP }}",
        sign:       False
      }
    - { extensions: "",
        filename:   "server",
        d_name:     "{{ MASTER_IP }}",
        sign:       True
      }
