# Copyright 2018 Walentin Lamonos lamonos@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---
# Install iptables package
- name: Install iptables
  apt:
    name: iptables
    state: latest

# Note: VMware machines already have this
- name: Copy default state of iptables
  copy:
    src: iptables-default
    dest: /root/iptables-default
  when: inventory_hostname not in groups['vmware-nodes']

# Again, VMWare machines already have this
- name: Apply default state of iptables
  shell: iptables-restore < iptables-default
  when: inventory_hostname not in groups['vmware-nodes']

- name: Setup master iptables
  import_tasks: setup_mastertables.yml
  when: inventory_hostname in groups['kubernetes-masters']

- name: Setup node iptables
  import_tasks: setup_nodetables.yml
  when: inventory_hostname in groups['kubernetes-nodes']
