---
- name: Check whether cert infrastructure needs setup
  stat:
    path: "/etc/ssl/gerdi/ca.key"
  register: ca_key_exists

# create canonical place for certs and keys on control machine
- name: Create directory for certs and keys on control machine
  file:
    path: "/etc/ssl/gerdi"
    state: directory
    owner: root
    group: root
    mode: 0500
  when: ca_key_exists.stat.exists == False

# create CA key and cert if it does not exist
- name: Create CA key
  command: openssl genrsa -out /etc/ssl/gerdi/ca.key 2048
  when: ca_key_exists.stat.exists == False

- name: Check for existing CA certificate file
  stat:
    path: "/etc/ssl/gerdi/ca.crt"
  register: ca_crt_exists

- name: Create CA certificate
  command: openssl req -x509 -new -nodes -key /etc/ssl/gerdi/ca.key -subj "/CN={{ MASTER_IP}}" -days 10000 -out /etc/ssl/gerdi/ca.crt
  when: ca_crt_exists.stat.exists == False

- name: Check whether server key exists
  stat:
    path: "/etc/ssl/gerdi/server.key"
  register: server_key_exists

- name: Create server key
  command: openssl genrsa -out /etc/ssl/gerdi/server.key 2048
  when: server_key_exists.stat.exists == False

- name: Check for existing server certificate file
  stat:
    path: "/etc/ssl/gerdi/server.crt"
  register: server_crt_exists

- name: Create server csr
  command: openssl req -new -key "/etc/ssl/gerdi/server.key" -subj "/CN={{ MASTER_IP }}" -out "/etc/ssl/gerdi/server.csr"
  when: server_crt_exists.stat.exists == False

- name: Sign server csr
  command: openssl x509 -req -in /etc/ssl/gerdi/server.csr -CA /etc/ssl/gerdi/ca.crt -CAkey /etc/ssl/gerdi/ca.key -CAcreateserial -out /etc/ssl/gerdi/server.crt -days 10000
  when: server_crt_exists.stat.exists == False
