# Copyright 2019 Walentin Lamonos lamonos@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: openstack-node | Set hostname to {{ inventory_hostname }}
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add all nodes to /etc/hosts with altIP, so kubelet exec functions correctly
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ hostvars[item]['altIP'] }} {{ item }}"
  with_items:
    - "{{ groups['kubernetes-masters'] }}"
    - "{{ groups['kubernetes-nodes'] }}"

- name: Remove update_etc_hosts from cloud config to make /etc/hosts reboot persistent
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    state: absent
    line: " - update_etc_hosts"

- name: Install necessary packages for OpenStack internal ip resolution
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - dnsmasq
  notify:
    - restart dnsmasq
  retries: 3
  delay: 3
