# Copyright 2019 Walentin Lamonos lamonos@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: openstack-node | Set hostname to {{ inventory_hostname }}
  hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: openstack-node | Check for presence of default /root/.ssh/authorized_keys
  shell: grep "no-agent-forwarding" /root/.ssh/authorized_keys | cat
  register: openstack_default_authorized_keys
  ignore_errors: yes
  check_mode: no
  become: true

- name: Delete default /root/.ssh/authorized_keys
  file:
    path: /root/.ssh/authorized_keys
    state: absent
  become: true
  when: openstack_default_authorized_keys.rc == 0

- name: Replace /root/.ssh/authorized_keys
  copy:
    src: "/home/{{ ansible_user }}/.ssh/authorized_keys"
    dest: /root/.ssh/authorized_keys
    remote_src: yes
  become: true
  when: openstack_default_authorized_keys.rc == 0

- name: Add all nodes to /etc/hosts with altIP, so kubelet exec functions correctly
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    state: present
    line: "{{ hostvars[item]['altIP'] }} {{ item }}"
  become: true
  with_items:
    - "{{ groups['kubernetes_masters'] }}"
    - "{{ groups['kubernetes_nodes'] }}"
    - "{{ groups['nfs_nodes'] }}"

- name: openstack-node | Remove update_etc_hosts from cloud config to make /etc/hosts reboot persistent
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    state: absent
    line: " - update_etc_hosts"
  become: true

- name: openstack-node | Install necessary packages for internal ip resolution
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - dnsmasq
  notify:
    - restart dnsmasq
  retries: 3
  delay: 3
  become: true
