# Copyright 2018 Tobias Weber weber@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# Description:
# This role sets up the kubernetes addon manager and handles the creation of the kube-dns service.
- name: k8s-addons | Label master machines
  shell: kubectl label nodes {{ inventory_hostname }} role=master --overwrite

- name: k8s-addons | Create addons dir
  file:
    path: /etc/kubernetes/addons
    state: directory

- name: k8s-addons | Create a yml-file to deploy kube-addon-manager
  template:
    src: "kube-addon-manager.yml.j2"
    dest: "{{ K8S_BASE_DIR }}/kube-addon-manager.yml"

- name: k8s-addons | Create kube-addon-manager
  shell: kubectl apply -f "{{ K8S_BASE_DIR }}/kube-addon-manager.yml"

- name: k8s-addons | Create manifests for all addons
  template:
    src:  "{{ item }}.yml.j2"
    dest: "/etc/kubernetes/addons/{{ item }}.yml"
  with_items:
    - "kube-dns"

- name: k8s-addons | Create kube-dns
  shell: kubectl apply -f /etc/kubernetes/addons/kube-dns.yml
