- name: Symlink scheduler to /usr/bin
  file:
    src:    "{{ K8S_SERVER_BIN_DIR }}/kube-scheduler"
    dest:   "/usr/bin/scheduler"
    state:  link

- name: Create a systemd unit file
  template:
    src: scheduler.service.j2
    dest: /etc/systemd/system/scheduler.service
  notify:
    - reload daemon
    - restart scheduler

- name: Register scheduler to systemd
  systemd:
    state: started
    name: scheduler
    enabled: yes
    daemon-reload: yes
