# Copyright 2018 Tobias Weber weber@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# Common tasks on every host
- name: Install additional requirements
  apt:
      pkg: "{{ item }}"
      state: latest
  with_items:
      - apt-transport-https
      - bash-completion
      - ca-certificates
      - curl
      - ipcalc
      - iproute2
      - python-dbus
      - python-dnspython
      - python-openssl

- name: Set hostname to {{ inventory_hostname }}
  hostname:
    name: "{{ inventory_hostname }}"

# TODO Take care of it in image (see SAI-242)
- name: Turn swapoff
  shell: swapoff -a

- name: Permanently turn swap off
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: "^/dev/sda1"

- name: Create k8s directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_items:
    - { path: "{{ K8S_BASE_DIR    }}", mode: '0755' }
    - { path: "{{ K8S_CERT_FILES_DIR  }}", mode: '0755' }
    - { path: "{{ K8S_AUTH_FILES_DIR  }}", mode: '0755' }
    - { path: "{{ K8S_KEY_FILES_DIR  }}", mode: '0700' }
    - { path: "/etc/kubernetes/manifests", mode: '0755' }

- name: Install script to determine interfaces, ips and gws
  copy:
    src: printIface.sh
    dest: /root/printIface.sh

- name: Retrieve information for first interface
  shell: bash /root/printIface.sh 1
  register: firstInterface

- name: Set facts for first interface
  set_fact:
    iface1:
      name: "{{ firstInterface.stdout.split(' ')[0] }}"
      ipv4: "{{ firstInterface.stdout.split(' ')[1] }}"
      gw: "{{ firstInterface.stdout.split(' ')[2] }}"
      nw: "{{ firstInterface.stdout.split(' ')[3] }}"
      hw: "{{ firstInterface.stdout.split(' ')[4] }}"

- name: Retrieve information for second interface
  shell: bash /root/printIface.sh 2
  register: secondInterface

- name: Set facts for second interface
  set_fact:
    iface2:
      name: "{{ secondInterface.stdout.split(' ')[0] }}"
      ipv4: "{{ secondInterface.stdout.split(' ')[1] }}"
      gw: "{{ secondInterface.stdout.split(' ')[2] }}"
      nw: "{{ secondInterface.stdout.split(' ')[3] }}"
      hw: "{{ secondInterface.stdout.split(' ')[4] }}"

- name: Retrieve information for third interface
  shell: bash /root/printIface.sh 3
  register: thirdInterface
  ignore_errors: yes

- name: Set facts for third interface
  set_fact:
    iface3:
      name: "{{ thirdInterface.stdout.split(' ')[0] }}"
      ipv4: "{{ thirdInterface.stdout.split(' ')[1] }}"
      gw: "{{ thirdInterface.stdout.split(' ')[2] }}"
      nw: "{{ thirdInterface.stdout.split(' ')[3] }}"
      hw: "{{ thirdInterface.stdout.split(' ')[4] }}"
  when: thirdInterface.rc != 100

- name: Set fact for internal address (on first run)
  set_fact:
    internalIP: "{{ iface3.ipv4 }}"
  when: thirdInterface.rc != 100

- name: Set fact for internal address (on second+ run)
  set_fact:
    internalIP: "{{ iface2.ipv4 }}"
  when: thirdInterface.rc == 100

- name: Install server key and cert
  copy:
    src:  "{{ item.src  }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src:  "{{ CONTROL_KEY_DIR}}/{{ inventory_hostname}}.key",
        dest: "{{ K8S_KEY_FILES_DIR }}/{{ inventory_hostname }}.key",
        mode: '0400' }
    - { src:  "{{ CONTROL_CERT_DIR}}/{{ inventory_hostname }}.crt.pem",
        dest: "{{ K8S_CERT_FILES_DIR }}/{{ inventory_hostname }}.crt.pem",
        mode: '0444' }
    - { src:  "{{ CONTROL_CERT_DIR}}/ca.crt.pem",
        dest: "{{ K8S_CERT_FILES_DIR }}/ca.crt.pem",
        mode: '0444' }
    - { src:  "{{ CONTROL_CERT_DIR}}/admin.crt.pem",
        dest: "{{ K8S_CERT_FILES_DIR }}/admin.crt.pem",
        mode: '0444' }
    - { src:  "{{ CONTROL_KEY_DIR}}/admin.key",
        dest: "{{ K8S_KEY_FILES_DIR }}/admin.key",
        mode: '0400' }
