---
# Common tasks on every host
- name: Install additional requirements 
  apt:
      pkg: "{{ item }}"
      state: latest
  with_items:
      - apt-transport-https
      - bridge-utils
      - ca-certificates
      - libnm-glib-dev
      - python-dbus
      - python3-dbus
      - python-networkmanager

