---
# Common tasks on every host
- name: Install requirements for adding new deb-repo packages & interactive ansible
  apt:
      pkg: "{{ item }}"
      state: latest
  with_items:
      - apt-transport-https
      - ca-certificates
      - python3-dbus
      - python-openssl
      - iproute2

- name: Create k8s directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_items:
    - { path: "{{ K8S_BASE_DIR    }}", mode: '0755' }
    - { path: "{{ CERT_FILES_DIR  }}", mode: '0755' }
    - { path: "{{ KEY_FILES_DIR  }}", mode: '0700' }

  #- name: get variables
  #debug: var=hostvars[inventory_hostname]

- name: Install certs
  copy:
    src:  "{{ CONTROL_CERT_DIR }}/ca.crt.pem"
    dest: "{{ CERT_FILES_DIR }}/ca.crt.pem"

- name: set hostname for master
  hostname:
    name: "{{ CLUSTER_NAME}}-mstr-{{hostname_suffix}}"
  when: inventory_hostname in groups['kubernetes-masters']

- name: set hostname for node
  hostname:
    name: "{{ CLUSTER_NAME}}-nd-{{hostname_suffix}}"
  when: inventory_hostname in groups['kubernetes-nodes']
