- name: Flush iptables rules
  iptables:
    table: nat
    flush: yes

- name: Delete default docker bridge
  nmcli:
    conn_name: docker0
    ifname: docker0
    type: bridge
    state: absent
  # Ignore error when trying to delete interface without connection
  ignore_errors: True

