- name: Flush iptables rules
  iptables:
    table: nat
    flush: yes

- name: Delete default docker bridge
  nmcli:
    conn_name: docker0
    ifname: docker0
    type: bridge
    state: absent
  # Ignore error when trying to delete interface without connection
  ignore_errors: True

#- name: purge any older docker server
#  apt:
#    pkg={{ item }}
#    state=absent
#    purge=yes
#    force=yes
#  with_items:
#    - docker.io
#    - lxc-docker
#    - docker-engine
#    - docker
#
#- name: update repository cache
#  apt:
#    update_cache: yes
#
#- name: install requirements for adding new deb-repo packages
#  apt:
#    pkg={{ item }}
#    state=present
#  with_items:
#    - apt-transport-https
#    - ca-certificates 
#    - curl
#    - software-properties-common
#
#- name: add the new gpg key
#  apt_key:
#      url: https://download.docker.com/linux/debian/gpg
#      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
#      state: present
#
#- name: add repo
#  apt_repository:
#    repo="deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}}  stable"
#    state=present
#
#- name: update repository cache
#  apt:
#    update_cache: yes
#
## TODO after testing this should not be latest but present with docher-ce=<tested_version>
#- name: install docker
#  apt: 
#      name: docker-ce
#      state: latest
#      install_recommends: yes
