# Copyright 2018 Tobias Weber weber@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# based on https://docs.docker.com/engine/installation/linux/docker-ce/debian/
- name: purge any older docker server
  apt:
    pkg={{ item }}
    state=absent
    purge=yes
    force=yes
  with_items:
    - docker.io
    - lxc-docker
    - docker-engine
    - docker

- name: update repository cache
  apt:
    update_cache: yes

- name: install requirements for adding new deb-repo packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: add the new gpg key
  apt_key:
      url: https://download.docker.com/linux/debian/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present

- name: add repo
  apt_repository:
    repo="deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}}  stable"
    state=present

- name: update repository cache
  apt:
    update_cache: yes

# TODO after testing this should not be latest but present with docker-ce=<tested_version>
- name: install docker
  apt:
      name: docker-ce
      state: latest
      install_recommends: yes

- name: Configure docker
  template:
    src:  "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
  notify:
    - restart docker
