---
- name: Symlink apiserver to /usr/bin
  file:
    src:    "{{ K8S_SERVER_BIN_DIR }}/kube-apiserver"
    dest:   "/usr/bin/apiserver"
    state:  link

- name: Create a systemd unit file
  template:
    src: apiserver.service.j2
    dest: /etc/systemd/system/apiserver.service
  notify:
    - restart apiserver

- name: Register apiserver to systemd
  systemd:
    state: started
    name: apiserver
    enabled: yes
    daemon-reload: yes
