---
- name: Create token file
  template:
    src:  "known_tokens.csv.j2"
    dest: "{{ K8S_AUTH_FILES_DIR }}/known_tokens.csv"

- name: Start apiserver as a pod
  import_tasks: apiserverAsPod.yml
  when: APISERVER_AS_POD

- name: Start apiserver as a service
  import_tasks: apiserverAsService.yml
  when: APISERVER_AS_SERVICE
