---
- name: Install api-server key and cert
  copy:
    src:  "{{ item.src  }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src:  "{{ CONTROL_KEY_DIR}}/apiserver.key",
        dest: "{{ KEY_FILES_DIR }}/apiserver.key",
        mode: '0400' }
    - { src:  "{{ CONTROL_CERT_DIR}}/apiserver.crt.pem",
        dest: "{{ CERT_FILES_DIR }}/apiserver.crt.pem",
        mode: '0444' }

- name: Create token file
  template:
    src:  "known_tokens.csv.j2"
    dest: "{{ AUTH_FILES_DIR }}/known_tokens.csv"

- name: Start apiserver as a pod
  import_tasks: apiserverAsPod.yml
  when: APISERVER_AS_POD

- name: Start apiserver as a service
  import_tasks: apiserverAsService.yml
  when: APISERVER_AS_SERVICE
