# Copyright 2018 Tobias Weber weber@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: network-ovn node | install ovs and ovn node packages
  package:
    name={{ item }}
  with_items:
    - ovn-host={{ OVN_HOST_VERSION }}

- name: network-ovn node | Secure connection to k8s API server
  shell: ovs-vsctl set Open_vSwitch . external_ids:{{item}}
  with_items:
    - k8s-api-server="https://{{ K8S_MASTER_IP }}:443"
    - k8s-ca-certificate={{ K8S_CERT_FILES_DIR }}/ca.crt.pem
    - k8s-api-token={{ OVN_API_TOKEN }}

- name: network-ovn node | Install ovn-k8s-node as a service
  template:
    src: ovn-k8s-node.service.j2
    dest: /etc/systemd/system/ovn-k8s-node.service
    force: no

# Restarts of this on !nodes! can fail if the bridge is already setup
# We can't ignore the error inside the systemd unit because we need to make sure
# ovn-kube-util runs on startup (this can fail on nodes if the master isn't up yet
# so allowing it to fail is important so systemd restarts it)
# However on a running machine, restarting it will then trigger an non zero code,
# because the bridge is already setup, this is why we ignore_errors here
- name: network-ovn node | Register ovn-k8s-node to systemd and start it
  systemd:
    name: ovn-k8s-node.service
    enabled: yes
    state: restarted
    daemon-reload: yes
  ignore_errors: yes

- name: network-ovn master | Restart ovn-k8s-master if master
  systemd:
    name: ovn-k8s-master.service
    state: restarted
  when: inventory_hostname in groups['kubernetes-masters']

# Install addons fixer after we have setup the ovn-master and its ovn-node
- name: network-ovn master | Install fix-k8s-addons script
  template:
    src: fix-k8s-addons.sh.j2
    dest: /etc/kubernetes/fix-k8s-addons.sh
  when: inventory_hostname in groups['kubernetes-masters']

- name: network-ovn master | Install fix-k8s-addons script as a service
  copy:
    src: ovn-k8s-addons-fix.service
    dest: /etc/systemd/system/ovn-k8s-addons-fix.service
  when: inventory_hostname in groups['kubernetes-masters']

- name: network-ovn master | Register fix-k8s-addons to systemd and start it
  systemd:
    name: ovn-k8s-addons-fix.service
    enabled: yes
    daemon-reload: yes
  when: inventory_hostname in groups['kubernetes-masters']
