# Copyright 2018 Tobias Weber weber@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: network-ovn master | install ovs and ovn master packages
  package:
    name={{ item }}
  with_items:
    - ovn-central={{ OVN_CENTRAL_VERSION }}

- name: network-ovn master | Create ovnnb and ovnsb certificates
  shell: |
    cd /etc/openvswitch &&
    ovs-pki req ovnnb && ovs-pki self-sign ovnnb &&
    ovs-pki req ovnsb && sudo ovs-pki self-sign ovnsb

- name: network-ovn master | Set SSL on ovnnb and ovnsb
  shell: |
    ovn-nbctl set-ssl /etc/openvswitch/ovnnb-privkey.pem \
    /etc/openvswitch/ovnnb-cert.pem /etc/openvswitch/cacert.pem &&
    ovn-sbctl set-ssl /etc/openvswitch/ovnsb-privkey.pem \
    /etc/openvswitch/ovnsb-cert.pem /etc/openvswitch/cacert.pem

- name: network-ovn master | open ports for ovn databases
  shell: |
    ovn-nbctl set-connection pssl:6641 &&
    ovn-sbctl set-connection pssl:6642
  changed_when: false

- name: network-ovn master | Set the k8s api server address in the Open vSwitch database
  shell: ovs-vsctl set Open_vSwitch . external_ids:k8s-api-server="https://{{ K8S_MASTER_IP }}:443"

- name: network-ovn master | Install ovn-k8s-master as a service
  template:
    src: ovn-k8s-master.service.j2
    dest: /etc/systemd/system/ovn-k8s-master.service

- name: network-ovn master | Register ovn-k8s-master to systemd and start it
  systemd:
    name: ovn-k8s-master.service
    enabled: yes
    state: restarted
    daemon-reload: yes
