# Copyright 2018 Tobias Weber weber@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Add unstable for newer ovn-version
  apt_repository:
    repo: deb http://debian.mirror.lrz.de/debian unstable main
    state: present

- name: Install package pinning for newer ovn-version
  copy:
    src: ovnovs.pref
    dest: /etc/apt/preferences.d/ovnovs.pref

- name: Install ovn dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - openvswitch-switch
      - make
      - gcc

- name: Set db entries on both masters and nodes
  shell: ovs-vsctl set Open_vSwitch . external_ids:{{item}}
  with_items:
    - ovn-remote="tcp:{{ K8S_MASTER_IP }}:6642"
    - ovn-nb="tcp:{{ K8S_MASTER_IP }}:6641"
    - ovn-encap-ip="{{ internalIP }}"
    - ovn-encap-type="{{ OVN_ENCAP_TYPE }}"

- name: Pull and extract go lang
  unarchive:
    src: https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes

- name: Setup .profile to feature go lang binary
  lineinfile:
    dest: ~/.profile
    state: present
    line: 'export PATH=$PATH:/usr/local/go/bin'

- name: Setup .profile to feature CNIBINDIR (for make)
  lineinfile:
    dest: ~/.profile
    state: present
    line: 'export CNIBINDIR={{ CNI_DIR }}'

- name: Pull latest ovn kubernetes source
  git:
    repo: 'https://github.com/openvswitch/ovn-kubernetes'
    #repo: 'https://github.com/CM2Walki/ovn-kubernetes'
    #version: "port-already-exists-fix"
    dest: "{{ OVN_K8S_DIR }}"

# This would be nicer using the make module, but it doesn't load the .profile context
- name: Make latest ovn
  shell: source ~/.profile && cd "{{ OVN_K8S_DIR }}/go-controller" && make
  args:
    executable: /bin/bash

- name: Make install latest ovn
  shell: source ~/.profile && cd "{{ OVN_K8S_DIR }}/go-controller" && make install
  args:
    executable: /bin/bash

# Taken from:
# https://github.com/openvswitch/ovn-kubernetes/blob/f7051630b8630ab3d592ca964e6e3d7ee07ae680/contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
- name: Ensure /etc/hosts is updated
  lineinfile:
    path: /etc/hosts
    line: "{{ internalIP }} {{ inventory_hostname }}"

# Gets rid of $OVS_CTL_OPTS in service file ExecStart
# Fixes issue:
# ovs-ctl[259]: /usr/share/openvswitch/scripts/ovs-ctl: exactly one non-option argument required (use --help for help)
- name: Fix openvswitch-nonetwork.service to make it succeed on reboot
  replace:
    path: /lib/systemd/system/openvswitch-nonetwork.service
    regexp: '\-\-system\-id\=random \$OVS_CTL_OPTS'
    replace: '--system-id=random'

- name: Create OVN configuration
  template:
    src: ovn_k8s.conf.j2
    dest: /etc/openvswitch/ovn_k8s.conf
