# Copyright 2018 Tobias Weber weber@lrz.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: network-ovn common | Add unstable for newer ovn-version
  apt_repository:
    repo: deb http://debian.mirror.lrz.de/debian unstable main
    state: present

- name: network-ovn common | Install package pinning for newer ovn-version
  copy:
    src: ovnovs.pref
    dest: /etc/apt/preferences.d/ovnovs.pref

- name: network-ovn common | Install ovn dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - openvswitch-switch={{ OPENVSWITCH_VERSION }}
      - make
      - gcc
  retries: 3
  delay: 3

- name: network-ovn common | Copy OVN CA cert
  copy:
    src: "{{ CONTROL_OVN_CA_DIR }}/switchca/cacert.pem"
    dest: "/etc/openvswitch/cacert.pem"
    mode: '0700'

- name: network-ovn common | Copy OVN host key
  copy:
    src: "{{ CONTROL_OVN_KEY_DIR }}/{{ inventory_hostname.split('.')[0] | lower }}-privkey.pem"
    dest: "/etc/openvswitch/ovn-privkey.pem"
    mode: '0700'

- name: network-ovn common | Copy OVN host cert
  copy:
    src: "{{ CONTROL_OVN_KEY_DIR }}/{{ inventory_hostname.split('.')[0] | lower }}-cert.pem"
    dest: "/etc/openvswitch/ovn-cert.pem"
    mode: '0700'

- name: network-ovn common | Set db entries on both masters and nodes
  shell: ovs-vsctl set Open_vSwitch . external_ids:{{item}}
  with_items:
    - ovn-nb="ssl:{{ K8S_MASTER_IP }}:6641"
    - ovn-remote="ssl:{{ K8S_MASTER_IP }}:6642"
    - ovn-encap-ip="{{ host_private_address | default(lookup('dig', inventory_hostname, 'qtype=A'), true) }}"
    - ovn-encap-type="{{ OVN_ENCAP_TYPE }}"

- name: network-ovn common | Check if ovn-kubernetes is already built
  stat:
    path: "{{ CNI_DIR }}/ovn-k8s-cni-overlay"
  register: stat_result

- name: network-ovn common | Pull and extract go lang
  unarchive:
    src: https://dl.google.com/go/{{ GOLANG_VERSION }}.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes
  retries: 3
  delay: 3
  when: stat_result.stat.exists == False

- name: network-ovn common | Setup .profile to feature go lang binary
  lineinfile:
    dest: ~/.profile
    state: present
    line: 'export PATH=$PATH:/usr/local/go/bin'

- name: network-ovn common | Setup .profile to feature CNIBINDIR (for make)
  lineinfile:
    dest: ~/.profile
    state: present
    line: 'export CNIBINDIR={{ CNI_DIR }}'

- name: network-ovn common | Pull latest ovn kubernetes source
  git:
    repo: 'https://github.com/openvswitch/ovn-kubernetes'
    version: "263952c21afec80e89b1048d8a6369c480540ec0"
    dest: "{{ OVN_K8S_DIR }}"
  retries: 3
  delay: 3
  when: stat_result.stat.exists == False

# This would be nicer using the make module, but it doesn't load the .profile context
- name: network-ovn common | Make latest ovn
  shell: source ~/.profile && cd "{{ OVN_K8S_DIR }}/go-controller" && make
  args:
    executable: /bin/bash
  when: stat_result.stat.exists == False

- name: network-ovn common | Make install latest ovn
  shell: source ~/.profile && cd "{{ OVN_K8S_DIR }}/go-controller" && make install
  args:
    executable: /bin/bash
  when: stat_result.stat.exists == False

# Taken from:
# https://github.com/openvswitch/ovn-kubernetes/blob/f7051630b8630ab3d592ca964e6e3d7ee07ae680/contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
- name: network-ovn common | Ensure /etc/hosts is updated
  lineinfile:
    path: /etc/hosts
    line: "{{ host_private_address | default(lookup('dig', inventory_hostname, 'qtype=A'), true) }} {{ inventory_hostname }}"

# Gets rid of $OVS_CTL_OPTS in service file ExecStart
# Fixes issue:
# ovs-ctl[259]: /usr/share/openvswitch/scripts/ovs-ctl: exactly one non-option argument required (use --help for help)
- name: network-ovn common | Fix openvswitch-nonetwork.service to make it succeed on reboot
  replace:
    path: /lib/systemd/system/openvswitch-nonetwork.service
    regexp: '\-\-system\-id\=random \$OVS_CTL_OPTS'
    replace: '--system-id=random'

# Remove dependency on networking.service on lb nodes
# Fixes issue:
# network.target: Job network.target/start deleted to break ordering cycle starting with openvswitch-switch.service/start
# (and therefore sshd service not starting)
- name: network-ovn loadbalancer | Fix openvswitch-switch.service to make sshd boot properly
  lineinfile:
    path: /lib/systemd/system/openvswitch-switch.service
    state: absent
    line: 'Before=networking.service'
  when: inventory_hostname in groups['loadbalancer_nodes']

- name: network-ovn common | Create OVN configuration
  template:
    src: ovn_k8s.conf.j2
    dest: /etc/openvswitch/ovn_k8s.conf
